---
title: "1_1"
output: html_notebook
---

# 读取数据
```{r}
titanic<-read.csv(file.choose())
```

# 查看数据
```{r}
summary(titanic)
head(titanic)
```
# 数据清洗
## 数据属性规范
```{r}
titanic$Pclass <- factor(titanic$Pclass) # 因子类型定义，分类变量
titanic$Embarked <- factor(titanic$Embarked)
titanic$Sex <- factor(titanic$Sex)
```
## 缺失值处理
```{r}
sum(is.na(titanic$Age))
sum(is.na(titanic$Cabin)) # 无法统计
```
# 导入库
```{r}
library(colorspace)
library(grid)
library(data.table)
library(VIM)
library(mice)
library(ggplot2)
```
# 可视化呈现
```{r}
NaPlot <- aggr(titanic, col=c("cyan","red"),numbers=TRUE,labels=names(data),cex.axis=.7,gap=3,ylab=c("Histogram of missing data","Pattern")) # 缺失信息可视化
```
```{r}
mean(titanic$Age,na.rm = T)
mean(titanic$Fare,na.rm = T)
titanic$Age[is.na(titanic$Age)] <- median(titanic$Age,na.rm = T)
titanic$Fare[is.na(titanic$Fare)] <- mean(titanic$Fare,na.rm = T)
titanic$Embarked[is.na(titanic$Embarked)] <- 'S'
summary(titanic)
```
# 导入训练和测试数据集
```{r}
train <- read.csv(file.choose())
test <- read.csv(file.choose())
str(train)
str(test)
```
## 处理训练集缺失值
```{r}
 train$Age[is.na(train$Age)] <- median(train$Age,na.rm = T)
 train$Fare[is.na(train$Fare)] <- mean(train$Fare,na.rm = T)
 train$Embarked[is.na(train$Embarked)] <- 'S' 
 test$Age[is.na(test$Age)] <- median(test$Age,na.rm = T)
```

# 导入数据包
```{r}
library(dplyr)
library(stringr)
library(caret)
library(randomForest)
```
## 1.船舱等级是否影响生还率

```{r}
Pclass_S <- table(train$Survived, train$Pclass)
Pclass_S_prop <- prop.table(Pclass_S, 2)
ggplot(data=train,aes(x=Pclass,fill=factor(Survived)))+geom_bar(stat="count",position='dodge')+scale_x_continuous(breaks=c(1:3))+labs(x='Pclass')
Pclass_S_prop
```
## 2.女士优先原则
```{r}
Sex_S <- table(train$Survived,train$Sex)
Sex_S_prop <- prop.table(Sex_S, 2)
ggplot(data=train,aes(x=Sex,fill=factor(Survived)))+geom_bar(stat ='count',position='dodge')
```
## 3. 年龄的影响
```{r}
Agedata <- as.numeric(unlist(train$Age))
Age_Level <- cut(Agedata,breaks=c(0,15,30,45,60,75,90),labels=c('kids','teenagers','prime','middle','agedness','senium'))
Age_S <- table(train$Survived, Age_Level)
Age_S_prop <- prop.table(Age_S, 2)
ggplot(data=data.frame(train$Survived,Agedata),aes(x=cut(Agedata,breaks = c(0,15,30,45,60,75,90)),fill=factor(train.Survived)))+geom_bar(stat='count',position='dodge')+labs(x='Age')+scale_x_discrete(labels=c('kids','teenagers','prime','middle','agedness','senium'))
```
## 4. 亲情与家庭影响：SibSp和Parch两个变量
```{r}
Sibsp_S <- table(train$Survived,train$SibSp)
Parch_S <- table(train$Survived,train$Parch)
Sibsp_S_prop <- prop.table(Sibsp_S,2)
Sibsp_S_prop <- prop.table(Parch_S,2)

ggplot(data=train,aes(x=SibSp,fill=factor(Survived)))+geom_bar(stat='count',position='dodge')+scale_x_continuous(breaks=c(0:8))+labs(x='Sibsp')

ggplot(data=train,aes(x=Parch,fill=factor(Survived)))+geom_bar(stat='count',position='dodge')+scale_x_continuous(breaks=c(0:6))+labs(x='Parch')

Families <- train$SibSp + train$Parch

ggplot(data=train,aes(x=Families,fill=factor(Survived)))+geom_bar(stat='count',position='dodge')+scale_x_continuous(breaks=c(0:10))+labs(x='Families')
```
## 5. 船舱票价与登船地点的影响
```{r}
Faredata <- as.numeric(unlist(train$Fare))
Fare_S <- table(train$Survived,cut(Faredata,breaks=c(0,50,100,600),labels=c('poor','middle','rich')))
Fare_S_prop <- prop.table(Fare_S,2)
ggplot(data=data.frame(train$Survived,Faredata),aes(x=cut(Faredata,breaks=c(0,50,100,600)),fill=factor(train.Survived)))+geom_bar(stat='count',position='dodge')+scale_x_discrete(labels=c('poor','middle','rich'))+labs(x='Fare')
Embarked_S <- table(train$Survived,train$Embarked)
Embraked_S_prop <- prop.table(Embarked_S,2)
ggplot(data=train,aes(x=Embarked,fill=factor(Survived)))+geom_bar(stat='count',position='dodge')
```
# 规律揭示或建模
```{r}
logistic <- glm(Survived~Pclass+Sex+Age+SibSp+Parch+Fare+Embarked,data= train[,-1],family='binomial'(link='logit'))
summary(logistic)
```
```{r}
set.seed(1029)
RF <- randomForest(factor(train$Survived)~.,data = train, importance=TRUE)
RF_tree <- plot(RF)
tree <- c(1:500)
OOB <- data.frame(tree,RF_tree)

ggplot(data=OOB,aes(x=tree))+geom_line(aes(y=OOB),colour='black',size=0.8)+geom_line(aes(y =X0),colour='red',size=0.8)+geom_line(aes(y=X1),colour="green",size=0.8)+labs(y="Error.rate")+theme_bw()
```
# 5 测试、预测与修正
## 测试集验证
```{r}
logistic2 <- glm(Survived ~Pclass+Sex+Age+SibSp,data = train[, -1],family = 'binomial'(link = 'logit'))
summary(logistic2)
test$predict <- predict(logistic2,test,type='response')
test$predictClass <- NULL
test$predictClass[test$predict >= 0.5] <- 1
test$predictClass[test$predict < 0.5] <- 0
test$predictClass[is.na(test$predict)] <- 0
Matrix1 <- table(test$Survived,test$predictClass)
Acc <- sum(diag(Matrix1))/sum(Matrix1)
Acc
```
## 测试集验证2
```{r}
pre_ran <- predict(RF,newdata=test)
obs_p_ran = data.frame(prob=pre_ran,obs=test$Survived) # 将真实值和预测值整合
Matrix2 <- table(test$Survived,pre_ran) # 输出混淆矩阵
Acc2 <- sum(diag(Matrix2))/sum(Matrix2)
Acc2
```

